s/PACKER-LOCALE-WITH-HYPHEN/en-AU/
s/PACKER-LOCALE-WITH-UNDERSCORE/en_AU/

s/PACKER-WINDOWS-TIMEZONE/Cen. Australia Standard Time/
s/PACKER-OSX-TIMEZONE/Australia\/Adelaide/
s/PACKER-OSX-DATEFORMAT/EEE MMM d  H:mm/

s/PACKER-OSX-METRIC/true/
s/PACKER-OSX-MEASUREMENT-UNITS/Centimeters/

s/PACKER-KEY-win7-pro/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win8-pro/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win81-pro/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win10-enterprise/XXXX-XXXX-XXXX-XXXX-XXXX/

s/PACKER-KEY-win2008-standard/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win2008r2-standard/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win2012-standard/XXXX-XXXX-XXXX-XXXX-XXXX/
s/PACKER-KEY-win2012r2-standard/XXXX-XXXX-XXXX-XXXX-XXXX/
